### ISSUE TITLE
Another Add-On/Extension that hides from the public

### ISSUE THREAD

**Issue by github2u** [FrostCo/AdvancedProfanityFilter#322]
I'll leave it here and hope for a miracle.  
I'm trying to set substitutions for profane words.  Not all I feel are profane.  But as soon as I bring up a word and set an option the Filter square that highlighted to indicate its being filtered, disappears.  Its really incomprehensible why so many tech geniuses lack basic common sense in design.  You people really need to ask around to normal thinking people to see if what you're doing makes any sense.  This doesn't.  Select your word, select what you want the extension to do with it and save your selection.  3 steps.  This seems like an insurmountable mountain for techies to grasp.  
If you want people to recognize your work it might be wise to actually think and ask others before releasing it.  In other words - check.

**Comment by richardfrost** [comment]
I'm sorry that you are having trouble with the filter, and getting support. There are many avenues that are available to ask questions, offer a suggestion, or to get help:

- Join the [APF Discord server](https://discord.gg/MpE5Z3f) (link inside the extension's option page, and also at the top of the [Project Readme](https://github.com/richardfrost/AdvancedProfanityFilter#readme))
- Send an email (shown at the top of the extension's help page)
- Use the [Chrome's extension](https://chrome.google.com/webstore/detail/advanced-profanity-filter/piajkpdbaniagacofgklljacgjhefjeh) support page
- Leave a review on whichever browser store you downloaded the filter from, because I read every review posted
- Open a Github [issue](https://github.com/richardfrost/AdvancedProfanityFilter/issues)
- Start (or join in) a Github [discussion](https://github.com/richardfrost/AdvancedProfanityFilter/discussions)

Since you found your way here, I'm happy to explore suggestions for improvement that you would like to present. I do have a group of users that have volunteered to provide feedback before updates are released, and many improvements have been made through those efforts. Currently, I'm not aware of any of them having issues configuring the filter to their use cases.

Unfortunately I can't make out exactly what it is you're advocating for in your message, but if there is something specific you'd like to propose I would be happy to consider it. Including screenshots can definitely help to illustrate the issue/shortcoming that you are seeing, and can be attached into your replies here.

I will also mention here, that although I try my best to be responsive and incorporate as many feature requests and suggestions as possible, I have other responsibilities in my life that come first. As the project creator/maintainer, I try my best to make this filter as useful to people as possible. I reserve the right to choose which features/updates will be worked on, and which will not. I'm definitely open for a discussion, and also love having multiple people sharing their thoughts on important issues.

**Comment by richardfrost** [comment]
I just re-read your post again, and I'm wondering if you are describing the "Filter" checkbox next to the Words & Phrases dropdown? If so, that check box is to filter the list of words (useful if the user doesn't want to see a long list of words they consider to be profane).

![image](https://user-images.githubusercontent.com/1507205/126215956-e4a7f2b4-31fe-4d5b-b427-a3c663162b9d.png)

I can adjust the wording there from `Filter` to something like `Filter list` if that might make it more clear as to its purpose.

If there is a word that you don't want to filter, you can select it from the list and then click the "Remove" button. If you'd like to make several modifications at one time, it might be a better experience to use the "Bulk Editor" found in the bottom right corner of the "Word" page.

**Comment by richardfrost** [comment]
One other question: Do you have a suggestion on how to make it easier to get help? Its not my attention to "hide from the public".

**Comment by github2u** [comment]
Here is the webpage apparently.  Where is the email address?
https://github.com/richardfrost/AdvancedProfanityFilter

And I joined Discord and posted my question.

All you need to do is post a Contact Us link on the Firefox Add-On area  
for your extension.
So many add-ons/extensions don't work properly and so rarely can we ask  
anyone for help.  There should be a forum so we can search others'  
questions so the author doesn't have to spend time answering questions.

So my question is regarding replacing the profane word with my choice.   
The top field (Words), once filled with the profane word, instantly  
switches to "Add, or update existing...."

Top field = butt
Word/Phrase = ass
Substitution = butt

Why is the top field even there?  I think I'm choosing what I want to  
replace "ass" with, right?  I think all I need is 2 fields.  The profane  
word and its replacement.  What am I missing?  No rush in answering.  By  
your answer here it shows you think very comprehensively so I'm sure it  
will be good so I look forward to your response.  I'm sure we'll get this  
ironed out.  Profanity filters have hugely improved the online experience  
for so many of us.

> I'm sorry that you are having trouble with the filter, and getting  
> support. There are many avenues that are available to ask questions,  
> offer a suggestion, or to get help:
>
> - Join the [APF Discord server](https://discord.gg/MpE5Z3f) (link inside  
> the extension's option page, and also at the top of the [Project  
> Readme](https://github.com/richardfrost/AdvancedProfanityFilter#readme))
> - Send an email (shown at the top of the extension's help page)
> - Use the [Chrome's  
> extension](https://chrome.google.com/webstore/detail/advanced-profanity-filter/piajkpdbaniagacofgklljacgjhefjeh)  
> support page
> - Leave a review on whichever browser store you downloaded the filter  
> from, because I read every review posted
> - Open a Github  
> [issue](https://github.com/richardfrost/AdvancedProfanityFilter/issues)
> - Start (or join in) a Github  
> [discussion](https://github.com/richardfrost/AdvancedProfanityFilter/discussions)
>
> Since you found your way here, I'm happy to explore suggestions for  
> improvement that you would like to present. I do have a group of users  
> that have volunteered to provide feedback before updates are released,  
> and many improvements have been made through those efforts. Currently,  
> I'm not aware of any of them having issues configuring the filter to  
> their use cases.
>
> Unfortunately I can't make out exactly what it is you're advocating for  
> in your message, but if there is something specific you'd like to  
> propose I would be happy to consider it. Including screenshots can  
> definitely help to illustrate the issue/shortcoming that you are seeing,  
> and can be attached into your replies here.
>
> I will also mention here, that although I try my best to be responsive  
> and incorporate as many feature requests and suggestions as possible, I  
> have other responsibilities in my life that come first. As the project  
> creator/maintainer, I try my best to make this filter as useful to  
> people as possible. I reserve the right to choose which features/updates  
> will be worked on, and which will not. I'm definitely open for a  
> discussion, and also love having multiple people sharing their thoughts  
> on important issues.

**Comment by github2u** [comment]
Attached is a screenshot from Win7 and latest Firefox.
In this instance I don't want any substitution for "ass".  I want it left  
alone.
I see no "remove" option anywhere on this page.  Maybe you were referring  
to another page.
I would have thought we select the word that is presently being filtered  
and deal with it by choosing substitution or maybe the first letter, etc.   
I don't know I select the initial word from the top field or the second  
one.  Once I input "ass" in the Word/Phrase field (why are there 2 fields  
for words and phrases???), I should be able to click an Ignore option if I  
don't want it to be affected.

And when we learn how to substitute words for the profane ones do we need  
to save each one individually?

> I just re-read your post again, and I'm wondering if you are describing  
> the "Filter" checkbox next to the Words & Phrases dropdown? If so, that  
> check box is to filter the list of words (useful if the user doesn't  
> want to see a long list of words they consider to be profane).
>
> ![image](https://user-images.githubusercontent.com/1507205/126215956-e4a7f2b4-31fe-4d5b-b427-a3c663162b9d.png)
>
> I can adjust the wording there from `Filter` to something like `Filter  
> list` if that might make it more clear as to its purpose.
>
> If there is a word that you don't want to filter, you can select it from  
> the list and then click the "Remove" button. If you'd like to make  
> several modifications at one time, it might be a better experience to  
> use the "Bulk Editor" found in the bottom right corner of the "Word"  
> page.
>

**Comment by github2u** [comment]
> One other question: Do you have a suggestion on how to make it easier to  
> get help? Its not my attention to "hide from the public".

Great to hear.
A Contact Us page is what most people use with a Captcha so we can send an  
internal message. Your email address displayed is risky I would think.   
You don't want that in the public domain.  They'll have your email address  
if you reply but very few spammers would bother with that I would think.

**Comment by github2u** [comment]
Match Method: Regex
Think what percentage of the population would have any clue what Regex  
means.  I'm guessing 1 in a thousand if they weren't into programming.   
You need to explain terms like this if they are not commonly used.  Or try  
to use a commonly used word.

I think providing a page of examples would be very good at explaining  
thing.  You start with:
Exact(dog: *** in the doghouse)

But you can do better than that.  Show a sentence with the word intact and  
the word substituted partially or whole or the first letter.  Nothing  
beats examples.  Its like showing them a picture.

You note that some people are sensitive, especially older women.  So one  
could just begin typing the word one doesn't want affected and it would  
pop up if in the index.

**Comment by richardfrost** [comment]
Alright, I'll try to answer everything in order so as to not lose all the context:

1. You are correct about not having my email address. Its only available in the Option's help page of the filter.
2. I didn't see your message on Discord, which channel did you put it in?
3. I have looked around the Firefox (Mozilla) developer dashboard and filled everything in there for the contact information that I can find. Could you share a screenshot or a link to the page its missing from so I can get it added?
4. As for a forum, Discord is probably the most direct/active place, and the [Github Discussions](https://github.com/richardfrost/AdvancedProfanityFilter/discussions) is probably the next best place, though it hasn't had as much activity yet (probably because it requires a Github account, which many users don't have). I'm open to other suggested venues for a forum, but aside from a Reddit or Facebook group I am not sure what else is out there. I'm looking for free as well, so that limits what is available.

Now on to the meat of the question:
The reason why there are 3 input elements (when substitution is enabled):
1. Add a new word, or modify/remove an existing word
2. This allows you to modify an existing word (say the above dropdown has "dog", but you want to change it to "cat"). Without this field (or trying to combine the first and second box) you would lose the ability to edit a word. It would be nicer if HTML had an element that could do both (basically an editable dropdown), but it doesn't. There are libraries out there that have filled this gap, but I haven't found one that is free that is also supported everywhere.
3. This input box is only available when the filter method is set to `Substitute`, and it represents the word that will replace a "filtered" word.


So, to remove a word:

1. Navigate to the "Words" page
2. Select the word from the `Words & Phrases` dropdown list
3. Click the remove button (bottom of the page)

![image](https://user-images.githubusercontent.com/1507205/126236269-f0e8041a-a492-4543-a070-244c7d983ae5.png)

As an alternative, you can also use the bulk editor (highlighted with green in the picture above) to rapidly make changes (remove multiple words, etc.).

To add a new word:

1. Navigate to the "Words" page
2. Leave the first dropdown on `Add, or update existing...`
3. Put the desired new word on second field (`newWord` in this example)
4. Add a substitution (`newSubstitution` in this example)
5. Adjust any other settings as desired (or leave with the defaults)
6. Click save. The form will then be reset (assuming everything is valid), and you can go modify another word, or close the options if you are done.

![image](https://user-images.githubusercontent.com/1507205/126236908-114048e4-036c-40fc-b66a-98e186371caf.png)

## Regex
I agree that more could be done, but I also don't want the page to be completely over-run with example text either. I do think the idea of having a link to a page with examples would probably work though. Surprisingly, there have actually been quite a few more users interested in the Regex match method than I expected. You are right that most don't though.

I also like that suggestion to have a fuzzy search element for finding the word, but unfortunately I haven't found a free, cross-platform element that is capable of that yet. I will take some time to look again soon.

P.S. It looks like the screenshot you attached doesn't come through the email, so if you want to share one you'll need to send a link to it in your text, or visit the Github issue and add it there in a reply.

**Comment by richardfrost** [comment]
Just wanted to follow up and see if you had any other thoughts on this, or had any answers to share from my last post. Thanks!

**Comment by richardfrost** [comment]
Going back to the conversation about the update notifications, I just released version 2.26.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.26.0) which turns off the update notification by default.

**Comment by github2u** [comment]
You're a rock star Richard!

> Going back to the conversation about the update notifications, I just  
> released version  
> [2.26.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.26.0)  
> which turns off the update notification by default.

**Comment by github2u** [comment]
> Just wanted to follow up and see if you had any other thoughts on this,  
> or had any answers to share from my last post. Thanks!

It was great for a while then I noticed all the words I had deleted from  
the list were back.  But it still chose to censor instead of the default  
substitute them so it only reset part of the changes.  I'll try to monitor  
it more closely.  The quick way for me is to remove all then add the few I  
find objectionable.

I don't understand "Wordlists".  They don't change anything.
What would look more sensible to me is an option to save those options and  
store them within the extension.  Nobody wants to store stuff somewhere  
else.  It often gets lost.  And its a pain to manage.  I thought if I  
saved a set of words as a Wordlist it would retain them but it doesn't  
seem to do anything at all.  When I click/activate a certain Wordlist the  
word list is exactly the same.

**Comment by richardfrost** [comment]
That's very odd that your settings got overridden again. Not sure what happened there. If you find out any other information on it let me know and I'll gladly look into it.

Wordlists are there for you to create a group or set of words tailored for a specific situation. For instance, you may have a different wordlist for children that might be more strict (include more words), or perhaps you frequent sites with a religious nature that you may not want to include all the words you've added. Or perhaps you have words you don't mind reading but would prefer not to hear while watching a video on a supported video site. You can set wordlists for specific sites, or set the default to be used everywhere else.

Note: Because the options page allows you to modify all the words stored in the extension, you will still see all the words in the list. This is expected behavior, so you can add new words to a wordlist. Another nice way to visualize your word settings is to use the Bulk Word Editor (Option Page > Words Tab > Bulk Editor button). There you can quickly adjust which words you want in each wordlist along with most of the other options.

If you haven't already, feel free to take a look at the short help topic about [Wordlists](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#wordlists).

**Comment by github2u** [comment]
OK thanks.  I'll work with that.  :)

> That's very odd that your settings got overridden again. Not sure what  
> happened there. If you find out any other information on it let me know  
> and I'll gladly look into it.
>
> Wordlists are there for you to create a group or set of words tailored  
> for a specific situation. For instance, you may have a different  
> wordlist for children that might be more strict (include more words), or  
> perhaps you frequent sites with a religious nature that you may not want  
> to include all the words you've added. Or perhaps you have words you  
> don't mind reading but would prefer not to hear while watching a video  
> on a supported video site. You can set wordlists for specific sites, or  
> set the default to be used everywhere else.
>
> Note: Because the options page allows you to modify all the words stored  
> in the extension, you will still see all the words in the list. This is  
> expected behavior, so you can add new words to a wordlist. Another nice  
> way to visualize your word settings is to use the Bulk Word Editor  
> (Option Page > Words Tab > Bulk Editor button). There you can quickly  
> adjust which words you want in each wordlist along with most of the  
> other options.
>
> If you haven't already, feel free to take a look at the short help topic  
> about  
> [Wordlists](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#wordlists).

**Comment by github2u** [comment]
Found something really odd I think.
First I removed all words.  (clicked Remove All).  Checked to make sure  
they were gone.
Refreshed the page.
All words are back.

> That's very odd that your settings got overridden again. Not sure what  
> happened there. If you find out any other information on it let me know  
> and I'll gladly look into it.
>
> Wordlists are there for you to create a group or set of words tailored  
> for a specific situation. For instance, you may have a different  
> wordlist for children that might be more strict (include more words), or  
> perhaps you frequent sites with a religious nature that you may not want  
> to include all the words you've added. Or perhaps you have words you  
> don't mind reading but would prefer not to hear while watching a video  
> on a supported video site. You can set wordlists for specific sites, or  
> set the default to be used everywhere else.
>
> Note: Because the options page allows you to modify all the words stored  
> in the extension, you will still see all the words in the list. This is  
> expected behavior, so you can add new words to a wordlist. Another nice  
> way to visualize your word settings is to use the Bulk Word Editor  
> (Option Page > Words Tab > Bulk Editor button). There you can quickly  
> adjust which words you want in each wordlist along with most of the  
> other options.
>
> If you haven't already, feel free to take a look at the short help topic  
> about  
> [Wordlists](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#wordlists).

**Comment by richardfrost** [comment]
If you look at the message that pops up after selecting "REMOVE ALL" you'll notice that it warns that will happen. That's because when all the words get removed, it reverts back to the default words. So it is working as designed, though maybe that message could be a bit more prominent.

If you only wanted to filter the word `hello`, you could remove all words, then promptly add the desired word. Then you should only have 1 word total in your list, and the defaults shouldn't come back (unless you were to remove `hello` again without adding another word).

Since there isn't a point of using the extension without any words, I think this is okay behavior.

**Comment by github2u** [comment]
> If you look at the message that pops up after selecting "REMOVE ALL"  
> you'll notice that it warns that will happen. That's because when all  
> the words get removed, it reverts back to the default words. So it is  
> working as designed, though maybe that message could be a bit more  
> prominent.
>
> If you only wanted to filter the word `hello`, you could remove all  
> words, then promptly add the desired word. Then you should only have 1  
> word total in your list, and the defaults shouldn't come back (unless  
> you were to remove `hello` again without adding another word).
>
> Since there isn't a point of using the extension without any words, I  
> think this is okay behavior.
----------
I totally missed that warning.  Why do this?  If someone does that maybe  
they are testing something.  It feels good doing a clean sweep after all.  
:)
Its never good to try to think for people.  Businesses constantly do that  
to all of us and its very insulting and demeaning.  I know you mean well,  
as they do, but it really wears on a person.  If you do, have a huge  
reminder but that should only appear once.

So I'm testing CCleaner.  That's the problem.  But now its deleting one of  
my 2 words.  Now I'm trying 5.  I restarted the browser to make sure they  
were still there.  They are.  Clean with the default ones checked.   
Restart Firefox to find 1 word left.

**Comment by richardfrost** [comment]
The reason the default words come back is because they are the defaults. Having no words means the defaults will be used. Said another way, the filter loads the user's settings, and if there are no words in their settings it uses the defaults.

The filter offers no utility without at least 1 word to filter, so I feel like with that note/warning probably does the job. It isn't the intention to force anything on the user, but like I said, the filter can't do anything without at least 1 word to watch for, so I don't think it's worth adjusting the current behavior. If a user doesn't want to filter any words, it would be much better to disable/uninstall the extension. And like the note says, you can remove all the words and then add one or more words to prevent defaults from being added again.

Good job continuing to test CCleaner. That's definitely an interesting outcome where it's selectively only removing parts of the config. I can't think why they would do that, but I hope you find the cause.

**Comment by github2u** [comment]
Well I tested it before and it did different things with the same  
settings.  So maybe there's something else in play but I can't imagine  
what.  I don't use any other "cleaners".  I don't even use any  
anti-virus.  Haven't had any problems in many years.  Of course I read my  
email in plain text and almost never open attachments.  The next time I  
test I'll do it with nothing else running except Firefox and CCleaner.   
And close as many background services as possible.  There's always some  
stragglers.

> The reason the default words come back is because they are the defaults.  
> Having no words means the defaults will be used. Said another way, the  
> filter loads the user's settings, and if there are no words in their  
> settings it uses the defaults.
>
> The filter offers no utility without at least 1 word to filter, so I  
> feel like with that note/warning probably does the job. It isn't the  
> intention to force anything on the user, but like I said, the filter  
> can't do anything without at least 1 word to watch for, so I don't think  
> it's worth adjusting the current behavior. If a user doesn't want to  
> filter any words, it would be much better to disable/uninstall the  
> extension. And like the note says, you can remove all the words and then  
> add one or more words to prevent defaults from being added again.
>
> Good job continuing to test CCleaner. That's definitely an interesting  
> outcome where it's selectively only removing parts of the config. I  
> can't think why they would do that, but I hope you find the cause.

**Comment by richardfrost** [comment]
Sorry its been so long [since you asked](https://github.com/richardfrost/AdvancedProfanityFilter/issues/322#issuecomment-963684122), but when you remove all words it does what it says. Thanks again for your feedback!

**Comment by throwaway-d** [comment]
Can this issue be closed now?

**Comment by github2u** [comment]
Sure. And thank you for your good work.  You are cleaning up our online  
world.

> Can this issue be closed now?
