### ISSUE TITLE
Insane Memory Usage On Safari

### ISSUE THREAD

**Issue by GameParrot** [FrostCo/AdvancedProfanityFilter#435]
#### :bug: Description
When using the extension, the RAM usage is insanely high, When running the test at https://browserbench.org/JetStream/, it goes over 4 GB with the extension and rarely over 600 MB without the extension.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Open Activity Monitor and switch to the Memory tab
2. Go to https://browserbench.org/JetStream/
3. Run the test
4. See the insane memory usage in Activity Monitor

#### :heavy_check_mark: Expected behavior
The memory usage should not be insanely high

#### :computer: Details
 - **Device:** iMac
 - **OS:** macOS 12.5.1
 - **Browser:** Safari
 - **Browser Version:** 15.6.1
 - **Affected site(s):** https://browserbench.org/JetStream/
 - **System RAM (total):** 16 GB

**Comment by richardfrost** [comment]
After a few tests with this, I don't really think there is anything that I can really do to prevent this. The memory usage appears to come as the its creating hundreds of new documents rapidly, and the browser injects a new instance of APF each time. The easiest fix here would probably be to just disable the extension for the page, because its working as its intended to. Benchmarks definitely push what they are benchmarking to their limits, and in this case that appears to be what is happening.

**Comment by GameParrot** [comment]
The extension seems to affect performance when browsing on sites even that are not benchmarks, especially ones with a lot of ads. Maybe disabling the extension on ads/iframes should be an option?

**Comment by richardfrost** [comment]
@GameParrot That's not a bad idea. I will add it to the backlog to look into that. My first thought is to implement it like the "Domain mode", which controls the overall strategy, and then allow specific domains to change that behavior.

**Comment by richardfrost** [comment]
Okay, this option has been added and should now be available in version [2.38.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.38.1). Let me know how it goes for you.
