### ISSUE TITLE
First issue I run into with this extension

### ISSUE THREAD

**Issue by m00dymann** [FrostCo/AdvancedProfanityFilter#529]
So I'm using an extension for the website Twitch called [Alternate Player for Twitch.tv] but I think this extension runs the website through the extension, and by doing so automatically disables the switch in [AdvancedProfanityFilter].

I've tried to add the URL to the domains in [AdvancedProfanityFilter] without any success.

**Comment by richardfrost** [comment]
Hi @m00dymann, just to be clear, are you saying that you are using APF with [Alternate Player for Twitch.tv](https://chromewebstore.google.com/detail/bhplkbgoehhhddaoolmakpocnenplmhf)? And when you have both, you can't enable APF on that page?

**Comment by richardfrost** [comment]
Oh, I think I see the problem @m00dymann. When I have that extension installed and go to watch a stream on Twitch, it takes me to a `chrome-extension://` URL, which unfortunately APF won't be able to access/run on. Extensions are sandboxed so that they can't directly interfere with each other, so there really isn't anything that I can do to further add support for that page. Sorry for the inconvenience.
