### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by Jtanner00** [FrostCo/AdvancedProfanityFilter#530]
Hi
I have this downloaded as an app on an iPhone. However, the list of websites that are allowed always open as apps which then doesn’t use the filter. 
How can I make this transfer over? 
Thank you

**Comment by richardfrost** [comment]
Hi @Jtanner00,

Thanks for reaching out about the iOS version of APF. Unfortunately not all the sites work on mobile due to the issue you mentioned where they redirect to the app. This is a decision made by those platforms and because of that there isn't much that can be done to circumvent it. There are a couple things you could try that have reportedly worked for some:
- Turn on "Request Desktop Site" for the site in Safari
- Uninstall the app (if installed)

I'm sorry that there isn't a bigger list of potential workarounds, and that there is some trial and error associated with it. As I mentioned above, it really is dependent on the streaming services, and they are make changes often. To make it even more complicated, streaming platforms have different policies for countries, so while Netflix may work just fine in England, it may not work in Canada (just an example).

If there is a specific site that isn't working for you I'd be happy to take a look and see if I can find anything more that could help, but it may be the case that it just can't be done right now.

**Comment by richardfrost** [comment]
You're welcome @Jtanner00.

Its possible that some sites may use a different mechanism for their captions/subtitles on mobile sites, so that could cause it to not work. My first troubleshooting question would be if you choose to hide the subtitles (Options page > Audio tab > Show only filtered), are they hidden on one of those custom sites? That will let us know if it is 

If there is an example you'd like to share, I'd be happy to take a look into it.

**Comment by Jtanner00** [comment]
I tried hiding the subtitles as well as starring profanity and it doesn’t
seem to be applying on the customized sites (it does work for the pre-added
ones). I’ll attach the code I have written.

{
 "losmovies.id": [
    {
      "className": "jw-text-track-container",
      "mode": "element",
      "subtitleSelector": "div.jw-text-track-cue",
      "tagName": "DIV"
    }
   ]
 }

Thank you

**Comment by richardfrost** [comment]
Hey @Jtanner00, sorry for the late response here, I'm in catch-up mode right now. As that isn't one of the officially supported sites, I can't say for sure what might be going on with it. If I had to guess though, you will likely need other custom config to go along with it, because the videos are actually played from another site. You might take a look at the [Additional Sites](https://github.com/FrostCo/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites) page and see if you find any there that might help.

**Comment by richardfrost** [comment]
I'm going to close this issue for now, but feel free to comment if you have more questions.
