### ISSUE TITLE
Audio Mute Not Working

### ISSUE THREAD

**Issue by RavioliShrek** [FrostCo/AdvancedProfanityFilter#535]
When I have the Audio Mute feature enabled, I watch Youtube Videos and the captions remove the bad word but the audio still doesn't mute. Can you please help me?

**Comment by richardfrost** [comment]
I'm sorry it isn't working for you @RavioliShrek. Can you share an example video where it isn't muting? Also, it might be worth temporarily disabling  the extension, turning the captions on and making sure that the word in question is actually in the captions. YouTube has had lots of different policies as to how it deals with profanity in captions, which is why it could be really helpful to have an example video (and approximate timestamp).

**Comment by RavioliShrek** [comment]
https://clipchamp.com/watch/azOVpX8Cq5l
Here is an example of it not muting. Thank you so much for responding! :)

**Comment by richardfrost** [comment]
You're welcome @RavioliShrek! Thanks for sharing that video. In the future if its easier feel free to just share a link to the YouTube video, but this worked in this case.

Unfortunately for this video it looks like the "F" word doesn't appear in the captions, so the filter won't able to work on this video. If you look at the video's captions without the filter being on, you'll see the text as follows:

```
different characters and Harry Potter each other
```

APF (the filter) is only as good as the accompanying captions. It seems strange to me that YouTube acknowledges and removes profanity from the captions, but allows it to play with the rest of the video. It may be possible for the channel owner to adjust their settings for generated captions to allow the profanity into the captions, btu I'm not sure how that works or if its even still possible as I don't have a YouTube channel.

**Comment by RavioliShrek** [comment]
Ah, alright thank you for the info!

**Comment by richardfrost** [comment]
You're welcome @RavioliShrek, sorry I don't have better news on that video.
