### ISSUE TITLE
MGM Plus is there a config for that site?

### ISSUE THREAD

**Issue by TruSteel** [FrostCo/AdvancedProfanityFilter#545]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

**Comment by TruSteel** [comment]
If you have a custome config for this site I would love to get it. Thank you

**Comment by richardfrost** [comment]
Hi @TruSteel, thanks for submitting a request for a new site. I took a look at it and think this config should work. If you have some time, please test it out and let me know how it works for you. If it works well, I'll add it to the official config as a supported site.

```json
{
  "www.mgmplus.com": [{
    "className": "bmpui-subtitle-region-container",
    "displaySelector": "div.bmpui-subtitle-region-container",
    "mode": "element",
    "subtitleSelector": "span.bmpui-ui-subtitle-label > span",
    "tagName": "DIV",
    "videoSelector": "video#bitmovinplayer-video-player-container"
  }]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

For best results, make sure to remove any custom config used for testing like this once it has been included in the official update.

**Comment by TruSteel** [comment]
Wow works great. Thank you very much.

**Comment by TruSteel** [comment]
After testing a few more movies, still doing good except for the movie The Gambler, it would mute just before the curse word so you would still hear the curse word.

**Comment by richardfrost** [comment]
Thanks for the update @TruSteel! I found an instance around 1:00:25 where the timing was off on the captions and it did let a word slip through. Unfortunately the filter is only able to filter based on when the captions appear and are removed, so if their timings are off it can cause problems.  One thing you can try is to change the Unmute Delay (Options page > Audio) to something like `0.5`, which will keep it muted for half a second longer. This will only help in situations where the captions are appearing ahead of the spoken words, and thus unmuting too early. Unfortunately we can't go the other direction because we don't have the caption data in advance,

One thing to note about `Unmute delay` is that it will be used on all sites, so you may need to adjust it for specific movies, and then reset it back to 0 on others if the timing is correct.

**Comment by TruSteel** [comment]
Thank you very much for your hard work and this info. I will definately give this a try.

**Comment by richardfrost** [comment]
This was added in Version [3.3.3](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.3.3).

If you used the "Custom config" in this issue, its recommend to remove the custom config once it has been included in the official update.
