### ISSUE TITLE
subtitles are blocked audio isn't

### ISSUE THREAD

**Issue by gandr5569** [FrostCo/AdvancedProfanityFilter#556]
Have been using this website forever. Movies are just getting to free with the cursing. I've installed your extension on Firefox for Android. I have a Galaxy Note S23 Ultra. Anything I try to watch the cc or subtitles are perfectly blocked - censored. None of the audio is though. I've been reading how to add a custom site. I'm a little new to all of this. If it is something somewhat easy to do, could you point me in the right direction.

**Comment by richardfrost** [comment]
Hi @gandr5569,

Thanks for reaching out! Are you trying to use it on one of the supported sites, or a new/custom one? Right now the method for creating a custom site rule can be quite challenging, but I'm happy to try and help you through it. What site(s) are you trying to filter videos on?

**Comment by gandr5569** [comment]
Trying to use it on a custom site. Primewire.pe Wife streams alot of
sitcoms and shows. We have grandchildren and today's writers thinks it's
great to fill their shows with a sailor's vocabulary.

**Comment by richardfrost** [comment]
Hi @gandr5569, can you give this custom config a try?

https://github.com/FrostCo/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites#site-primewirepe

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

Since this site is not officially supported, it may stop working at any time if they make a change, so always make sure to test it before relying on it. You may want to add a test word found in the captions to make sure it is working (remembering to remove that test word before watching the movie).

**Comment by gandr5569** [comment]
I will do. I thank you so much for the promt reply and help.
