### ISSUE TITLE
APF has stopped working completely. Filtering has stopped and settings is blank

### ISSUE THREAD

**Issue by idkwebdev** [FrostCo/AdvancedProfanityFilter#567]
#### :bug: Description

The popup is dropdowns are blank and the settings is blank apart from the navbar. Additionally, filtering has stopped. I believe it stopped working yesterday.

#### :twisted_rightwards_arrows: Steps To Reproduce

1. Open extension popup or settings
2. See error

#### :heavy_check_mark: Expected behavior

I expect for filtering to work and settings to show.

#### :camera: Screenshots

![image](https://github.com/user-attachments/assets/3d44b415-c99a-4ea9-8495-9b220089f2c7)
![image](https://github.com/user-attachments/assets/5a40cbaf-07c5-48d1-85cf-6b4f9ebbad37)

#### :computer: Details

- **Device:** Acer Aspire Laptop
- **OS:** Windows 11 
- **Browser:** MS Edge Beta
- **Browser Version:** Version 128.0.2739.9
- **Affected site(s):** Everything

**Comment by idkwebdev** [comment]
Understood. And thanks for your help.

**Comment by richardfrost** [comment]
@idkwebdev I haven't heard anything from the Edge team yet, so I went ahead and put the patch in place in [version 3.6.0](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.6.0). It has been published on the Chrome store which you can install it from in Edge, or you can wait until it completes the review process on the Edge store (sometimes it can take 3-5 days longer than Chrome). Once you get the 3.6.0 update let me know if you have any issues with still.

**Comment by idkwebdev** [comment]
It seems to be working now. Btw, I did send feedback to Microsoft regarding this issue. They didn't respond to me either. In any case, thanks for the help.

**Comment by Quipyowert2** [comment]
I am having the same problem, but in Firefox instead of Edge. This problem started months ago, but I didn't make a note at the time of which Firefox version the problem started in.

I uninstalled and reinstalled the addon, but the Settings page is still blank. I've been using the same Firefox profile for years. I guess I should try switching Firefox profiles and/or Windows users and then install APF and see if settings page works.

Do I need to submit the bug to Mozilla as well?

💻 Details
*   Device: MSI GS63 Stealth 8RE Laptop
*   OS: Windows 10 22H2 (19045.5371) x86_64
*   Graphics card: nVidia GTX 1060 and Intel UHD 630
*   Screen resolution: 1920x1080
*   Browser: Firefox
*   Browser Version: Version 134.0.2 (64-bit)
*   Affected site(s): Everything

**Comment by richardfrost** [comment]
Hi @Quipyowert2,

If it isn't working on your older profile but does work on a new one, to me that means it must be something related to data. Do you still have the broken profile around? If so, it would really help me if you could open up the popup or settings page and inspect it (right click menu > inspect). I'm pretty sure some error should show up, and hopefully that can help me address it. Up till now, I've gotten some scattered reports of this happening, but I haven't ever seen it happen myself, and I haven't been able to explain it either.

**Comment by Quipyowert2** [comment]
The APF settings page works now in my old profile after uninstalling and reinstalling the addon a second time. I found where the indexedDB is located (`${PROFILE}/storage/permanent/chrome/idb` [according to Reddit](https://www.reddit.com/r/firefox/comments/by0olj/how_can_i_delete_all_data_for_a_specific_addon/)) and I was going to try to figure out which sqlite file corresponds to the addon and delete it, but I guess I don't need to.
